"use client";

import { useState } from "react";
import { signIn } from "next-auth/react";
import { useRouter } from "next/navigation";
import { LogIn, Mail, Lock, Loader2 } from "lucide-react";
import { BrandLogo } from "@/components/BrandMark";

export default function LoginPage() {
  const router = useRouter();
    const [email, setEmail] = useState("");
      const [password, setPassword] = useState("");
        const [error, setError] = useState("");
          const [loading, setLoading] = useState(false);

            async function handleSubmit(e: React.FormEvent) {
                e.preventDefault();
                    setLoading(true);
                        setError("");
                            const res = await signIn("credentials", { email, password, redirect: false });
                                setLoading(false);
                                    if (res?.error) {
                                          setError("E-mail ou senha inválidos.");
                                                return;
                                                    }
                                                        router.push("/dashboard");
                                                            router.refresh();
                                                              }

                                                                return (
                                                                    <div className="flex min-h-screen items-center justify-center bg-brand-hero px-4 py-12">
                                                                          <div className="w-full max-w-md">
                                                                                  <div className="mb-8 flex flex-col items-center text-center">
                                                                                            <BrandLogo priority width={260} height={260} className="mb-3 h-auto w-40 drop-shadow-2xl" />
                                                                                                                            <h1 className="text-3xl font-bold text-white">KidSaber Connect</h1>
                                                                                                                                      <p className="mt-2 text-teal-100">Entre para acessar o sistema da clínica</p>
                                                                                                                                              </div>
                                                                                                                                              
                                                                                                                                                      <div className="card p-8">
                                                                                                                                                                <form onSubmit={handleSubmit} className="space-y-5">
                                                                                                                                                                            <div>
                                                                                                                                                                                          <label className="label">E-mail</label>
                                                                                                                                                                                                        <div className="relative">
                                                                                                                                                                                                                        <Mail className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                              value={email}
                                                                                                                                                                                                                                                                                                                onChange={(e) => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                  placeholder="voce@exemplo.com"
                                                                                                                                                                                                                                                                                                                                                    className="input pl-10"
                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                        <label className="label">Senha</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="relative">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Lock className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="input pl-10"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="rounded-lg bg-coral-50 px-3 py-2 text-sm text-coral-700">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button type="submit" disabled={loading} className="btn-primary w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <LogIn className="h-4 w-4" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Entrar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-6 text-center text-sm text-teal-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Acesso restrito à equipe e responsáveis da Clínica KidSaber.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
